fiest pass of the new makecert, still work in progress

diff --git a/makecert b/makecert
--- a/makecert
+++ b/makecert
@@ -67,6 +67,17 @@ _text_before_start="This script will create your certificate based on your own C
 _need_root=0
 _need_lock=1
 
+# color :)
+_reset_color='\033[0m'				# Text Reset
+_color_bold_black='\033[1;30m'		# Black
+_color_bold_red='\033[1;31m'		# Red
+_color_bold_green='\033[1;32m'		# Green
+_color_bold_yellow='\033[1;33m'		# Yellow
+_color_bold_blue='\033[1;34m'		# Blue
+_color_bold_purple='\033[1;35m'		# Purple
+_color_bold_cyan='\033[1;36m'		# Cyan
+_color_bold_white='\033[1;37m'		# White
+
 # working variables
 _opid=$$
 _hostname="${HOSTNAME%%.*}"
@@ -75,73 +86,71 @@ _lockfile="$_work_dir/$_program".LOCK
 _work_cert="$_work_dir/mkcert.cfg"
 _echo_flag='-e'
 _openssl=openssl
+_debug=0
+_san_cert=0
 
 # Cert Variables
 if [[ -f env ]] ; then
 	source ./env
 else
-	_my_country="US"
-	_my_state="Colorado"
-	_my_city="Fort Collins"
-	_my_org="Badassops LLC"
-	_my_email="hostmaster@badassops.com"
-	_my_valid_days=1830 # 5 years :)
-	_my_sec_size=4096
-	_my_req_pass='77BlueDog.'
-	_my_domain=
+	echo $_echo_flag "\t$_color_bold_purple ** no env file found"
+	echo $_echo_flag "\tyou will need to enter the cert detail manually **$_reset_color"
 fi
-# need to capture now so we can use it for clean_up_upon_fail
-_my_cert_name="$1"
-_cert_files="${_my_cert_name}.crt ${_my_cert_name}.csr ${_my_cert_name}.key ${_my_cert_name}.key.crypt ${_my_cert_name}.pass"
-
-# Set interrupt handler
-trap inthandler 1 2 3 4 5 9 10 12 15 23 24 25
 
 function inthandler() {
+	echo $_echo_flag "\n$_color_bold_red\t!!! Something when wrong or Control-C was press, deleting all certs file for $_my_cert_name !!!$_reset_color"
 	clean_up_upon_fail
 	clean_up
 	echo $_echo_flag "$_cancelled"
 	exit 0
 }
 
+function clean_up() {
+	rm -rf "$_work_dir" > /dev/null 2>&1
+	return 0
+}
+
 function clean_up_upon_fail() {
-	echo $_echo_flag "\t!!! Something when wrong or Control-C was press, deleting all certs file for $_my_cert_name !!!"
 	for _cert_file in $_cert_files
 	do
 		# interrupted before files were move under the certs directory
 		[[ -f "$_cert_file" ]] && rm -f "$_cert_file" > /dev/null 2>&1
 		# interrupted after files were move under the certs directory
-		[[ -f certs/"$_cert_file" ]] && rm -f certs/"$_cert_file" > /dev/null 2>&1
+		[[ -f real_certs/"$_cert_file" ]] && rm -f real_certs/"$_cert_file" > /dev/null 2>&1
 	done
 	return 0
 }
+
+# Set interrupt handler
+trap inthandler 1 2 3 4 5 9 10 12 15 23 24 25
 
 function clean_up_cert() {
-	_cert_files="${1}.crt ${1}.csr ${1}.key ${1}.key.crypt ${1}.pass"
 	for _cert_file in $_cert_files
 	do
-		[[ -f certs/"$_cert_file" ]] && rm -f certs/"$_cert_file" > /dev/null 2>&1
+		# interrupted before files were move under the certs directory
+		[[ -f "$_cert_file" ]] && rm -f "$_cert_file" > /dev/null 2>&1
+		# interrupted after files were move under the certs directory
+		[[ -f real_certs/"$_cert_file" ]] && rm -f real_certs/"$_cert_file" > /dev/null 2>&1
 	done
-	return 0
-}
-
-function clean_up() {
-	rm -f "$_lockfile" > /dev/null 2>&1
 	return 0
 }
 
 function help() {
 	trap 1 2 3 4 5 9 10 12 15 23 24 25
 	echo $_echo_flag "$_info"
-	echo $_echo_flag "Usage : $_program [-h] name-for-cert"
-	echo $_echo_flag "Example: $_program www.suryo.com"
+	echo $_echo_flag "Usage : $_program [-h][-s] cert-domain"
+	echo $_echo_flag "\n\tUse the keyword $_color_bold_red wildcard$_reset_color,$_color_bold_red star$_reset_color or$_color_bold_red *$_reset_color, for wildcard cert"
+	echo $_echo_flag "\texample: $_program wildcard.suryo.com"
+	echo $_echo_flag "\n\tuse -s for a SAN supporting cert, default is no SAN."
+	echo $_echo_flag "\tyou can add up too 3 {sub}domains"
+	echo $_echo_flag "\texample: $_program -s wildcard.suryo.com alpha.dev.suryo.com alpha.dev.suryo.io omega.dev.suryo.us"
 	clean_up
 	exit 0
 }
 
 function isRoot() {
 	if (($(id -u) != 0)) ; then
-		echo $_echo_flag "\n\t*** $_program: this script must be run as the user root ***\n" >&2
+		echo $_echo_flag "$_color_bold_red\n\t $_program: this script must be run as the user root $_reset_color\n" >&2
 		return 1
 	fi
 	return 0
@@ -149,38 +158,83 @@ function isRoot() {
 
 function check_running() {
 	if [[ -f "$_lockfile" ]]; then
-		echo $_echo_flag "*** There is already a $_program running, execution has been terminated. ***"
-		echo $_echo_flag "*** If this is an error please remove the lock file: $_lockfile. ***"
-		exit 2
+		/bin/ps -p $(cat $_lockfile) > /dev/null 2>&1
+		if (( $? == 0 )) ; then
+			echo $_echo_flag "*** There is already a $_program running, execution has been terminated. ***"
+			echo $_echo_flag "*** If this is an error please remove the lock file: $_lockfile ***"
+			exit $_state_ok
+		else
+			echo $_echo_flag "*** Lock file found and deleted since there is no process with that pid ***"
+			rm -rf $_lockfile > /dev/null 2>&1
+		fi
 	fi
 	if ! mkdir -p "$_work_dir" > /dev/null 2>&1;then
-		echo $_echo_flag "*** $_state_unknown_msg: Unable to create file working directory $_work_dir! ***"
-		exit 2
+		echo $_echo_flag "*** $_state_critical_msg: Unable to create file working directory $_work_dir! ***"
+		exit $_state_unknown
 	fi
 	echo "$_opid" > "$_lockfile"
 	return 0
 }
 
+function get_given_options() {
+	local _option_san=0
+	local _has_error=0
+	case "$1" in
+		'-s'|'--san'|'-san')			_san_cert=1 ; shift ; let _option_san++ ;;
+		'-h'|'--help'|'-help')			help ; exit $_state_ok ;;
+		'-v'|'--version'|'-version')	echo $_echo_flag "$_version" ; exit $_state_ok ;;
+		'-c'|'-cleanup'|'-cleanup')		clean_up_cert ; exit $_state_ok ;;
+	esac
+	(( $_option_san > 1 )) && echo $_echo_flag "\n\t: -s can only be given once." && help
+	[[ -z $1 ]] && help
+	_given_cert_name="$1"
+	if [[ "$_given_cert_name" =~ ^(wildcard|star|\*).* ]] ; then
+		_my_base_cert_name="${_given_cert_name#*\.}"
+		_my_cert_name="*.${_my_base_cert_name}"
+		_subject_alt_name="DNS:$_my_cert_name"
+		_my_cert_crt=wildcard."$_my_base_cert_name".crt
+		_my_cert_key=wildcard."$_my_base_cert_name".key
+		_my_cert_csr=wildcard."$_my_base_cert_name".csr
+		_my_cert_pass=wildcard."$_my_base_cert_name".pass
+	else
+		_my_base_cert_name="$_given_cert_name"
+		_my_cert_name="$_given_cert_name"
+		_subject_alt_name="DNS:$_my_cert_name"
+		_my_cert_crte="$_my_cert_name".crt
+		_my_cert_key="$_my_cert_name".key
+		_my_cert_csr="$_my_cert_name".csr
+		_my_cert_pass="$_my_cert_name".pass
+	fi
+	_cert_files="$_my_cert_crt $_my_cert_key $_my_cert_csr $_my_cert_pass ${_my_cert_key}.crypt"
+	if (( $_option_san == 1 )) ; then
+		shift
+		_san_domains="$@"
+		for _san_domain in $_san_domains
+		do
+			_subject_alt_name="$_subject_alt_name, DNS:$_san_domain"
+		done
+	fi
+	return 0
+}
+
 function setup_env() {
 	# make sure environment exists
-	[[ ! -f ca.crt ]] && return 1
-	[[ ! -f ca.key ]] && return 1
-	[[ ! -f ca.serial ]] && echo '01' > ca.serial
+	[[ ! -d real_certs ]] && mkdir -p real_certs
 	return 0
 }
 
 function create_key() {
-	echo $_echo_flag "\t*** Generating RSA private key for SERVER ($_my_sec_size bit) [${_my_cert_name}.key] ***"
-	$_openssl genrsa -out "$_my_cert_name".key $_my_sec_size > /dev/null 2>&1
-	(( $? != 0 )) && return 1
+	echo $_echo_flag "$_color_bold_cyan\t Generating RSA private key for SERVER ($_my_sec_size bit) [${_my_cert_key}] $_reset_color"
+	if (( $_debug == 0 )) ; then
+		$_openssl genrsa -out "$_my_cert_key" $_my_sec_size > /dev/null 2>&1
+		(( $? != 0 )) && return 1
+		echo $_echo_flag "$_color_bold_cyan\t created$_reset_color\n"
+	fi
 	return 0
 }
 
 function create_csr() {
-	echo $_echo_flag "\t*** Generating X.509 certificate request for SERVER [${_my_cert_name}.csr] ***"
-	echo $_echo_flag "\t**************************************************************"
-	echo $_echo_flag "\t********** DO NOT USE SAME PASSWORD AS THE KEY FILE **********"
-	echo $_echo_flag "\t**************************************************************"
+	echo $_echo_flag "\t$_color_bold_cyan Generating X.509 certificate request for SERVER [${_my_cert_csr}]$_reset_color"
 cat > $_work_cert <<EOT
 [ req ]
 default_bits					= $_my_sec_size
@@ -188,30 +242,29 @@ distinguished_name				= req_distinguished_name
 attributes						= req_attributes
 string_mask						= utf8only
 req_extensions					= v3_req
+utf8							= yes
 
 [ req_distinguished_name ]
-countryName						= "1. Country Name             (2 letter code)"
+countryName						= "1. Country Name (2 letter code)"
 countryName_default				= $_my_country
 countryName_min					= 2
 countryName_max					= 2
-stateOrProvinceName				= "2. State or Province Name   (full name)    "
+stateOrProvinceName				= "2. State or Province Name (full name)"
 stateOrProvinceName_default		= $_my_state
-localityName					= "3. Locality Name            (eg, city)     "
+localityName					= "3. Locality Name (eg, city)"
 localityName_default			= $_my_city
-0.organizationName				= "4. Organization Name        (eg, company)  "
+0.organizationName				= "4. Organization Name (eg, company)"
 0.organizationName_default		= $_my_org
-organizationalUnitName			= "5. Organizational Unit Name (eg, section)  "
+organizationalUnitName			= "5. Organizational Unit Name (eg, section)"
 organizationalUnitName_default	=
-commonName						= "6. Common Name              (eg, fqdn)     "
+commonName						= "6. Common Name (eg, fqdn)"
 commonName_max					= 64
 commonName_default				= $_my_cert_name
-emailAddress					= "7. Email Address            (eg, name@fqdn)"
+emailAddress					= "7. Email Address (eg, name@fqdn)"
 emailAddress_max				= 40
 emailAddress_default			= $_my_email
 
 [ req_attributes ]
-challengePassword				= "The password for the request file"
-challengePassword_default		= $_my_req_pass
 challengePassword_min			= 4
 challengePassword_max			= 20
 unstructuredName				= "Organization Name"
@@ -220,12 +273,29 @@ unstructuredName_default		= $_my_org
 [ v3_req ]
 basicConstraints				= CA:FALSE
 keyUsage						= nonRepudiation, digitalSignature, keyEncipherment
-subjectAltName					= DNS:$_my_cert_name
+subjectAltName					= $_subject_alt_name
 EOT
 
-	$_openssl req -nodes -config $_work_cert -new -key "$_my_cert_name".key -out "$_my_cert_name".csr -extensions v3_req
-	(( $? != 0 )) && return 1
+	if (( $_debug == 0 )) ; then
+		echo $_echo_flag "$_color_bold_cyan\t Password set is $_color_bold_purple$_my_req_pass $_reset_color\n"
+		$_openssl req -nodes -config $_work_cert -new -key "$_my_cert_key" -out "$_my_cert_csr" -extensions v3_req
+		(( $? != 0 )) && return 1
+	else
+		cat $_work_cert
+	fi
 	rm -f $_work_cert
+	return 0
+}
+
+function check_cert() {
+	echo $_echo_flag "$_color_bold_cyan\t Enrypting RSA private key of SERVER with a pass phrase for security [${_my_cert_key}] $_reset_color"
+	if (( $_debug == 0 )) ; then
+		$_openssl rsa -des3 -in "$_my_cert_key" -out "$_my_cert_key".crypt > /dev/null 2>&1
+		if (( $? != 0 )) ; then
+			echo $_echo_flag "$_color_bold_red\t!!!! $_program Error: Failed to Enrypting RSA private key of CA with a pass phrase !!!!$_reset_color"
+			return 1
+		fi
+	fi
 	return 0
 }
 
@@ -301,7 +371,7 @@ function check_cert() {
 	return 0
 }
 
-function make_it() {
+function create_it() {
 	create_key
 	(( $? != 0 )) && return 1
 	create_csr
@@ -311,48 +381,39 @@ function make_it() {
 	check_cert
 	(( $? != 0 )) && return 1
 
-	# create the password file for the cert, so we have it in case we forgot the password.
-	mv ${_my_cert_name}* certs/
-	echo $_echo_flag "\t*** About to Create the password file for the CA cert, so we have it in case we forgot the password ***"
-	echo -n "Enter the same password one more time.."
-	stty -echo
-	read in_key
-	stty echo
-	echo "$in_key" > certs/"$_my_cert_name".pass
-	echo "Server ${_my_cert_name}'s CERT created and ready for use....."
+	if (( $_debug == 0 )) ; then
+		# create the password file for the cert, so we have it in case we forgot the password.
+		mv ${_my_cert_name}* real_certs/
+		echo $_echo_flag "\n$_color_bold_cyan\t About to Create the password file for the csr and key, so we have it in case we forgot the password $_reset_color"
+		echo -en "\t${_color_bold_yellow} Enter the same password one more time :$_reset_color "
+		stty -echo
+		read in_key
+		stty echo
+		echo "$in_key" > real_certs/"$_my_cert_pass"
+		echo $_echo_flag "\n\t$_color_bold_green ${_my_cert_name}'s CERT created and ready for use.....$_reset_color"
+	fi
 	return 0
 }
 
 function main() {
-	# secret flag :)
-	case $1
-	in
-		cleanup)	clean_up_cert $2 ; exit 0 ;;
-		-h|--help)	help ; exit 0 ;;
-	esac
-
-	[[ $# != 1 ]] && help
-	setup_env
-	if (( $? != 0 )) ; then
-		echo $_echo_flag "\t!!! Seems like the CA was not set yet, please run makeca..."
-		exit 1
-	fi
-
+	local _result=0
 	if (( $_need_root == 1 )) ; then
 		 isRoot
 		(( $? != 0 )) && echo $_echo_flag "$_info" && exit 255
 	fi
 	(( $_need_lock == 1 )) && check_running
+	get_given_options $@
+	setup_env
 
 	echo $_echo_flag "$_text_before_start"
-	echo $_echo_flag "Press Enter to continue or Control-C to cancel..."
+	echo $_echo_flag "$_color_bold_yellow\tPress Enter to continue or Control-C to cancel...$_reset_color"
 	read inKey
-	make_it
+	create_it
 	_result=$?
-
 	(( $_result == 1 )) && clean_up_upon_fail
 	clean_up
 	trap 1 2 3 4 5 9 10 12 15 23 24 25
 	exit $_result
 }
 main "$@"
+
